
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavvlyrsaonpacuufhbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdnZseXJzYW9ucGFjdXVmaGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDI3MTQsImV4cCI6MjA2MzMxODcxNH0.Xnh9V6YpoChx-PPH_6MM0Ud5qYgrr1hQrSGizPHlkD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
